FROM nginx:1.14.1-alpine

ARG NGINX_CONF=nginx/gui.conf
ENV NGINX_CONF=$NGINX_CONF

## Remove default nginx configs
RUN rm -rf /etc/nginx/conf.d/*

## Copy our default nginx config
#COPY nginx/polkascan.conf /etc/nginx/conf.d/
COPY ${NGINX_CONF} /etc/nginx/conf.d/

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

##  copy the artifacts to default nginx public folder
COPY ./dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
